{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "# load pd df from csv of jlc_parts.csv\n",
    "\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "# load csv\n",
    "df = pd.read_csv('jlc_parts.csv', sep=',', header=0, index_col=0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'Manufacturer': 'STMicroelectronics',\n",
       " 'MFR.Part #': 'VIPER53-DIP-E',\n",
       " 'JLCPCB Part #': 'C10050',\n",
       " 'Package': 'DIP-8',\n",
       " 'Description': '300kHz 620V 8.4V~19V DIP-8  AC-DC Controllers & Regulators ROHS',\n",
       " 'Datasheet': 'Download',\n",
       " 'Source': 'JLCPCB',\n",
       " 'Assembly Type': 'Wave SolderingA PCB assembly fixture is needed to protect and support this part during the assembly process.',\n",
       " 'CAD Model': 'PCB Footprint or Symbol',\n",
       " 'Stock': 0,\n",
       " 'Price': [('1+', 0.3444),\n",
       "  ('10+', 0.2814),\n",
       "  ('30+', 0.2544),\n",
       "  ('100+', 0.2207),\n",
       "  ('500+', 0.2057),\n",
       "  ('1000+', 0.1967)]}"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "\n",
    "def get_lcsc_data(lcsc_id):\n",
    "    # Construct the URL\n",
    "    url = f'https://jlcpcb.com/partdetail/{lcsc_id}'\n",
    "    \n",
    "    # Get the HTML content\n",
    "    response = requests.get(url)\n",
    "    \n",
    "    # Check if the request was successful\n",
    "    if response.status_code != 200:\n",
    "        return None  # Or some error handling\n",
    "\n",
    "    # Parse the HTML content\n",
    "    soup = BeautifulSoup(response.text, 'html5lib')\n",
    "    \n",
    "    # Dictionary to store the data\n",
    "    part_details = {}\n",
    "\n",
    "    # Extracting general details\n",
    "    for dl in soup.find_all('dl', class_='flex dl-list'):\n",
    "        dt = dl.find('dt').get_text(strip=True)\n",
    "        dd = dl.find('dd').get_text(strip=True)\n",
    "        part_details[dt] = dd\n",
    "\n",
    "    # Extracting stock information\n",
    "    stock_info = soup.find(\"div\", class_=\"text-16 font-bold\")\n",
    "    stock = int(stock_info.text.strip().split(': ')[1]) if stock_info else None\n",
    "    part_details['Stock'] = stock\n",
    "\n",
    "    # Extracting price information\n",
    "    price_divs = soup.find_all(\"div\", class_=\"flex items-center justify-between mt-14\")\n",
    "    price = []\n",
    "    for div in price_divs:\n",
    "        qty = div.find(\"span\", class_=\"w-120 inline-block\").text.strip()\n",
    "        pr = div.find(\"span\", class_=\"w-120 text-left\").text.strip().replace('$', '')\n",
    "        price.append((qty, float(pr)))\n",
    "    part_details['Price'] = price\n",
    "\n",
    "    # Check if 'JLCPCB Part #' is empty\n",
    "    if not part_details.get('JLCPCB Part #'):\n",
    "        return None\n",
    "\n",
    "    return part_details\n",
    "\n",
    "# Test the function with a specific lcsc_id\n",
    "lcsc_id = \"C10050\"\n",
    "data = get_lcsc_data(lcsc_id)\n",
    "# print(data)\n",
    "data\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "C11266 not found\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-5 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "NameError: name 'db' is not defined\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "C14433 not found\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-29 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "NameError: name 'db' is not defined\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "C11900 not found\n",
      "C35333 not found\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-27 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "NameError: name 'db' is not defined\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "C20766 not foundC10000 not found\n",
      "\n",
      "C21400 not found\n",
      "C26466 not found\n",
      "C12533 not found\n",
      "C13166 not found\n",
      "C13800 not found\n",
      "C27100 not found\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Thread-35 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "NameError: name 'db' is not defined\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "C111333 not foundC97400 not found\n",
      "\n",
      "C93600 not found\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Exception in thread Thread-194 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-135 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-168 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Thread-148 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-20 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-140 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-158 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-175 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-211 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-154 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-99 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-82 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-100 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-247 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-124 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-16 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-155 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-143 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-192 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-191 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-252 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-161 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-246 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-89 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-196 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "Exception in thread Thread-198 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-205 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-231 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-293 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-172 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-151 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-112 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-62 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-279 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-236 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-176 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-265 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-28 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-70 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-183 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-85 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-221 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-72 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "Exception in thread Thread-103 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-253 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "Exception in thread Thread-131 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-116 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-203 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-235 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-257 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-212 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-104 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-234 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-118 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-266 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-274 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-214 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-174 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-276 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-122 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-215 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-167 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-41 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-157 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-283 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-208 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-230 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-153 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-187 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-210 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-259 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-242 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "Exception in thread Thread-254 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-275 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-229 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-146 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-270 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-263 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-218 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-222 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-127 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-285 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "Exception in thread Thread-64 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-88 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-149 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-271 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-225 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "Exception in thread Thread-114 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-294 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-190 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-130 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "Exception in thread Thread-109 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "Exception in thread Thread-206 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "Exception in thread Thread-267 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-8 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-217 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-141 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-245 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-18 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-71 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "Exception in thread Thread-152 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "Exception in thread Thread-23 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-255 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "Exception in thread Thread-281 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-264 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-244 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-61 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "NameError: name 'db' is not defined\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "Exception in thread Thread-84 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "Exception in thread Thread-220 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "Exception in thread Thread-280 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-260 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-209 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-111 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "NameError: name 'db' is not defined\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-241 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "NameError: name 'db' is not defined\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "Exception in thread Thread-177 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "NameError: name 'db' is not defined\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "NameError: name 'db' is not defined\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "NameError: name 'db' is not defined\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "NameError: name 'db' is not defined\n",
      "Exception in thread Thread-189 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-126 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "Exception in thread Thread-184 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "Exception in thread Thread-258 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "NameError: name 'db' is not defined\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "Exception in thread Thread-9 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "Exception in thread Thread-243 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "Exception in thread Thread-173 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "NameError: name 'db' is not defined\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "NameError: name 'db' is not defined\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-188 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "NameError: name 'db' is not defined\n",
      "Exception in thread Thread-76 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "NameError: name 'db' is not defined\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "NameError: name 'db' is not defined\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "Exception in thread Thread-202 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-233 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-120 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "NameError: name 'db' is not defined\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "NameError: name 'db' is not defined\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "NameError: name 'db' is not defined\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "NameError: name 'db' is not defined\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "Exception in thread Thread-238 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "NameError: name 'db' is not defined\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "Exception in thread Thread-30 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "Exception in thread Thread-102 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "NameError: name 'db' is not defined\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "NameError: name 'db' is not defined\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "Exception in thread Thread-171 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "NameError: name 'db' is not defined\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "NameError: name 'db' is not defined\n",
      "Exception in thread Thread-261 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-216 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "Exception in thread Thread-150 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "NameError: name 'db' is not defined\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "NameError: name 'db' is not defined\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "NameError: name 'db' is not defined\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "NameError: name 'db' is not defined\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "NameError: name 'db' is not defined\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "NameError: name 'db' is not defined\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "NameError: name 'db' is not defined\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "NameError: name 'db' is not defined\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "NameError: name 'db' is not defined\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "Exception in thread Thread-240 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "Exception in thread Thread-207 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "NameError: name 'db' is not defined\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "Exception in thread Thread-90 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "Exception in thread Exception in thread Thread-159 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "C179733 not foundC77133 not found\n",
      "\n",
      "C120833 not found\n",
      "C16333 not found\n",
      "C48633 not found\n",
      "C30266 not found\n",
      "C35966 not found\n",
      "C45466 not found\n",
      "C194300 not found\n",
      "C197466 not found\n",
      "C58133 not found\n",
      "C31533 not found\n",
      "C133500 not found\n",
      "C138566 not found\n",
      "C54333 not found\n",
      "C34066 not found\n",
      "C100566 not found\n",
      "C191766 not found\n",
      "C68266 not found\n",
      "C44200 not found\n",
      "C39133 not found\n",
      "C89166 not found\n",
      "C158833 not found\n",
      "C32166 not found\n",
      "C15700 not found\n",
      "C42300 not found\n",
      "C49900 not found\n",
      "C47366 not found\n",
      "C32800 not found\n",
      "C64466 not found\n",
      "C106266 not found\n",
      "C182900 not found\n",
      "C40400 not found\n",
      "C67000 not found\n",
      "C129700 not found\n",
      "C142366 not found\n",
      "C86633 not found\n",
      "C81566 not found\n",
      "C28366 not found\n",
      "C121466 not found\n",
      "C108166 not found\n",
      "C69533 not found\n",
      "C132233 not found\n",
      "C165166 not found\n",
      "C50533 not found\n",
      "C94866 not found\n",
      "C58766 not found\n",
      "C95500 not found\n",
      "C149333 not found\n",
      "C79033 not found\n",
      "C56866 not found\n",
      "C39766 not found\n",
      "C85366 not found\n",
      "C37233 not found\n",
      "C51166 not found\n",
      "C49266 not found\n",
      "C37866 not found\n",
      "C189866 not found\n",
      "C56233 not found\n",
      "C108800 not found\n",
      "C36600 not found\n",
      "C80300 not found\n",
      "C15066 not found\n",
      "C14434 not found\n",
      "C196833 not found\n",
      "C92333 not found\n",
      "C190500 not found\n",
      "C195566 not found\n",
      "C53700 not found\n",
      "C114500 not found\n",
      "C41033 not found\n",
      "C68900 not found\n",
      "C61933 not found\n",
      "C34700 not found\n",
      "C42933 not found\n",
      "C82833 not found\n",
      "C125266 not found\n",
      "C115766 not found\n",
      "C183533 not found\n",
      "C73966 not found\n",
      "C11901 not found\n",
      "C177833 not found\n",
      "C16966 not found\n",
      "C189233 not found\n",
      "C66366 not found\n",
      "C115133 not found\n",
      "C194933 not found\n",
      "C169600 not found\n",
      "C112600 not found\n",
      "C177200 not found\n",
      "C23933 not found\n",
      "C21401 not found\n",
      "C166433 not found\n",
      "C65100 not found\n",
      "C154400 not found\n",
      "C99300 not found\n",
      "C75233 not found\n",
      "C19500 not found\n",
      "C122100 not found\n",
      "C110066 not found\n",
      "C134133 not found\n",
      "C198733 not found\n",
      "C30900 not found\n",
      "C122733 not found\n",
      "C91700 not found\n",
      "C22666 not found\n",
      "C192400 not found\n",
      "C151233 not found\n",
      "C124633 not found\n",
      "C23300 not found\n",
      "C120200 not found\n",
      "C44833 not found\n",
      "C199366 not found\n",
      "C136666 not found\n",
      "C38500 not found\n",
      "C54966 not found\n",
      "C188600 not found\n",
      "C150600 not found\n",
      "C67633 not found\n",
      "C196200 not found\n",
      "C157566 not found\n",
      "C27733 not found\n",
      "C41666 not found\n",
      "C57500 not found\n",
      "C186066 not found\n",
      "C111966 not found\n",
      "C98666 not found\n",
      "C74600 not found\n",
      "C180366 not found\n",
      "C134766 not found\n",
      "C62566 not found\n",
      "C71433 not found\n",
      "C43566 not found\n",
      "C187333 not found\n",
      "C20767 not found\n",
      "C84100 not found\n",
      "C75866 not found\n",
      "C65733 not found\n",
      "C173400 not found\n",
      "C198100 not found\n",
      "C11267 not found\n",
      "C18233 not found\n",
      "C88533 not found\n",
      "C191133 not found\n",
      "C91066 not found\n",
      "C45467 not found\n",
      "C94233 not found\n",
      "C194301 not found\n",
      "C48634 not found\n",
      "C27101 not found\n",
      "C191767 not found\n",
      "C60033 not found\n",
      "C10001 not found\n",
      "C164533 not found\n",
      "C151866 not found\n",
      "C148700 not found\n",
      "C29000 not found\n",
      "C130966 not found\n",
      "C89167 not found\n",
      "C120834 not found\n",
      "C94867 not found\n",
      "C110700 not found\n",
      "C35334 not found\n",
      "C86634 not found\n",
      "C13801 not found\n",
      "C165800 not found\n",
      "C149334 not found\n",
      "C31534 not found\n",
      "C21402 not found\n",
      "C142367 not found\n",
      "C93601 not found\n",
      "C92334 not found\n",
      "C27734 not found\n",
      "C158834 not found\n",
      "C165167 not found\n",
      "C37234 not found\n",
      "C16334 not found\n",
      "C15067 not found\n",
      "C68267 not found\n",
      "C69534 not found\n",
      "C197467 not found\n",
      "C114501 not found\n",
      "C35967 not found\n",
      "C41667 not found\n",
      "C177201 not found\n",
      "C188601 not found\n",
      "C182901 not found\n",
      "C68901 not found\n",
      "C81567 not found\n",
      "C195567 not found\n",
      "C23301 not found\n",
      "C150601 not found\n",
      "C179734 not found\n",
      "C194934 not found\n",
      "C106267 not found\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "NameError: name 'db' is not defined\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "NameError: name 'db' is not defined\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "NameError: name 'db' is not defined\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "NameError: name 'db' is not defined\n",
      "Thread-63 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "Exception in thread Thread-200 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "NameError: name 'db' is not defined\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "NameError: name 'db' is not defined\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "Exception in thread Thread-147 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "NameError: name 'db' is not defined\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "NameError: name 'db' is not defined\n",
      "Exception in thread Thread-39 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "Exception in thread Thread-7 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "Exception in thread Thread-128 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "Exception in thread Thread-165 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "Exception in thread Thread-55 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "NameError: name 'db' is not defined\n",
      "Exception in thread Thread-282 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "NameError: name 'db' is not defined\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "Exception in thread Thread-53 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "Exception in thread Thread-237 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "Exception in thread Thread-251 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "NameError: name 'db' is not defined\n",
      "Exception in thread Thread-219 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "NameError: name 'db' is not defined\n",
      "Exception in thread Thread-273 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "NameError: name 'db' is not defined\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "Exception in thread Thread-170 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "NameError: name 'db' is not defined\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "NameError: name 'db' is not defined\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "NameError: name 'db' is not defined\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "Exception in thread Thread-204 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "Exception in thread Thread-144 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 29, in add_to_firestore\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_28524/1362866264.py\", line 42, in scrape_range\n",
      "NameError: name 'db' is not defined\n",
      "NameError: name 'db' is not defined\n",
      "    self.run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 982, in run\n",
      "Exception in thread Thread-21 (scrape_range):\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py\", line 1045, in _bootstrap_inner\n"
     ]
    }
   ],
   "source": [
    "# get_lcsc_data('C1529')\n",
    "\n",
    "# put in firestore\n",
    "import firebase_admin\n",
    "from firebase_admin import credentials\n",
    "from firebase_admin import firestore\n",
    "\n",
    "# Use a service account.\n",
    "cred = credentials.Certificate('atopile-880ca67acfe2.json')\n",
    "\n",
    "app = firebase_admin.initialize_app(cred)\n",
    "\n",
    "db = firestore.client()\n",
    "\n",
    "# Function to add data to Firestore\n",
    "# Function to add data to Firestore\n",
    "# Function to add data to Firestore with the 'JLCPCB Part #' as the document name\n",
    "def add_to_firestore(collection_name, data_dict):\n",
    "    # Extract the 'JLCPCB Part #' to use as the document ID\n",
    "    doc_id = data_dict.get('JLCPCB Part #')\n",
    "    if not doc_id:\n",
    "        raise ValueError(\"Missing 'JLCPCB Part #' in the data dictionary\")\n",
    "\n",
    "    # Transform nested arrays if necessary (e.g., 'Price' field)\n",
    "    if 'Price' in data_dict:\n",
    "        data_dict['Price'] = [{'quantity': p[0], 'price': p[1]} for p in data_dict['Price']]\n",
    "    \n",
    "    # Specify the document ID and set the data\n",
    "    collection_ref = db.collection(collection_name).document(doc_id)\n",
    "    collection_ref.set(data_dict)\n",
    "\n",
    "\n",
    "\n",
    "# Use the function\n",
    "# part_data = get_lcsc_data('C1529')\n",
    "# add_to_firestore('unparsed-parts', part_data)\n",
    "    \n",
    "def scrape_range(start, end):\n",
    "    for x in range(start, end):\n",
    "        part_data = get_lcsc_data(f'C{x}')\n",
    "        if part_data:\n",
    "            add_to_firestore('unparsed-parts', part_data)\n",
    "            print(f'C{x} added')\n",
    "        else:\n",
    "            print(f'C{x} not found')\n",
    "\n",
    "# Create threads to scrape the parts in parallel\n",
    "from threading import Thread\n",
    "\n",
    "# Define the number of threads\n",
    "num_threads = 300\n",
    "min_part_id = 10000\n",
    "max_part_id = 200000\n",
    "\n",
    "# Create the threads\n",
    "threads = []\n",
    "for i in range(num_threads):\n",
    "    start = min_part_id + i * (max_part_id - min_part_id) // num_threads\n",
    "    end = min_part_id + (i + 1) * (max_part_id - min_part_id) // num_threads\n",
    "    threads.append(Thread(target=scrape_range, args=(start, end)))\n",
    "\n",
    "# Start the threads\n",
    "for thread in threads:\n",
    "    thread.start()\n",
    "\n",
    "# Wait for the threads to finish\n",
    "for thread in threads:\n",
    "    thread.join()\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 135,
   "metadata": {},
   "outputs": [
    {
     "ename": "TypeError",
     "evalue": "WebDriver.__init__() got an unexpected keyword argument 'executable_path'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[135], line 33\u001b[0m\n\u001b[1;32m     30\u001b[0m     \u001b[38;5;66;03m# Close the webdriver\u001b[39;00m\n\u001b[1;32m     31\u001b[0m     driver\u001b[38;5;241m.\u001b[39mquit()\n\u001b[0;32m---> 33\u001b[0m \u001b[43mget_lcsc_data\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mC1529\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m)\u001b[49m\n",
      "Cell \u001b[0;32mIn[135], line 6\u001b[0m, in \u001b[0;36mget_lcsc_data\u001b[0;34m(lcsc_id)\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mget_lcsc_data\u001b[39m(lcsc_id):\n\u001b[1;32m      5\u001b[0m     \u001b[38;5;66;03m# Setup the webdriver\u001b[39;00m\n\u001b[0;32m----> 6\u001b[0m     driver \u001b[38;5;241m=\u001b[39m \u001b[43mwebdriver\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mChrome\u001b[49m\u001b[43m(\u001b[49m\u001b[43mexecutable_path\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43m/path/to/chromedriver\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m)\u001b[49m  \u001b[38;5;66;03m# replace with your path\u001b[39;00m\n\u001b[1;32m      8\u001b[0m     \u001b[38;5;66;03m# Load the webpage\u001b[39;00m\n\u001b[1;32m      9\u001b[0m     driver\u001b[38;5;241m.\u001b[39mget(\u001b[38;5;124mf\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mhttps://jlcpcb.com/partdetail/\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mlcsc_id\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m'\u001b[39m)  \u001b[38;5;66;03m# replace with your URL\u001b[39;00m\n",
      "\u001b[0;31mTypeError\u001b[0m: WebDriver.__init__() got an unexpected keyword argument 'executable_path'"
     ]
    }
   ],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 98,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/var/folders/xl/r_y6qlm504l70lmz99q_ndfw0000gn/T/ipykernel_12779/2858623272.py:43: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.\n",
      "  specs_header = soup.find('nav', text='Specifications')\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "{'Manufacturer': 'UNI-ROYAL(Uniroyal Elec)',\n",
       " 'MFR.Part #': '0402WGF1002TCE',\n",
       " 'JLCPCB Part #': 'C25744',\n",
       " 'Package': '0402',\n",
       " 'Description': '62.5mW Thick Film Resistors ±100ppm/℃ ±1% 10kΩ 0402  Chip Resistor - Surface Mount ROHS',\n",
       " 'Datasheet': 'Download',\n",
       " 'Source': 'JLCPCB',\n",
       " 'Assembly Type': 'SMT AssemblyA PCB assembly fixture is needed to protect and support this part during the assembly process.',\n",
       " 'CAD Model': 'PCB Footprint or Symbol',\n",
       " 'Stock': 9655804,\n",
       " 'Price': [('1+', 0.0005),\n",
       "  ('1000+', 0.0004),\n",
       "  ('3000+', 0.0003),\n",
       "  ('10000+', 0.0003),\n",
       "  ('50000+', 0.0002),\n",
       "  ('50200+', 0.0002)]}"
      ]
     },
     "execution_count": 98,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "\n",
    "def get_lcsc_data(lcsc_id):\n",
    "    # Construct the URL\n",
    "    url = f'https://jlcpcb.com/partdetail/{lcsc_id}'\n",
    "    \n",
    "    # Get the HTML content\n",
    "    response = requests.get(url)\n",
    "    \n",
    "    # Check if the request was successful\n",
    "    if response.status_code != 200:\n",
    "        return None  # Or some error handling\n",
    "\n",
    "    # Parse the HTML content\n",
    "    soup = BeautifulSoup(response.text, 'html.parser')\n",
    "    \n",
    "    # Dictionary to store the data\n",
    "    part_details = {}\n",
    "\n",
    "    # Extracting general details\n",
    "    for dl in soup.find_all('dl', class_='flex dl-list'):\n",
    "        dt = dl.find('dt').get_text(strip=True)\n",
    "        dd = dl.find('dd').get_text(strip=True)\n",
    "        part_details[dt] = dd\n",
    "\n",
    "    # Extracting stock information\n",
    "    stock_info = soup.find(\"div\", class_=\"text-16 font-bold\")\n",
    "    stock = int(stock_info.text.strip().split(': ')[1]) if stock_info else None\n",
    "    part_details['Stock'] = stock\n",
    "\n",
    "    # Extracting price information\n",
    "    price_divs = soup.find_all(\"div\", class_=\"flex items-center justify-between mt-14\")\n",
    "    price = []\n",
    "    for div in price_divs:\n",
    "        qty = div.find(\"span\", class_=\"w-120 inline-block\").text.strip()\n",
    "        pr = div.find(\"span\", class_=\"w-120 text-left\").text.strip().replace('$', '')\n",
    "        price.append((qty, float(pr)))\n",
    "    part_details['Price'] = price\n",
    "\n",
    "    # Extracting specific attributes from the specifications table\n",
    "    # First find the 'Specifications' header\n",
    "    specs_header = soup.find('nav', text='Specifications')\n",
    "    if specs_header:\n",
    "        # Then find the table following this header\n",
    "        spec_tables = specs_header.find_all('div', class_='el-table__body-wrapper').find('table')\n",
    "        for spec_table in spec_tables:\n",
    "            for row in spec_table.find_all('tr', class_='el-table__row'):\n",
    "                cells = row.find_all('div', class_='cell')\n",
    "                if len(cells) == 2:\n",
    "                    attr_name = cells[0].text.strip()\n",
    "                    attr_value = cells[1].text.strip()\n",
    "                    part_details[attr_name] = attr_value\n",
    "\n",
    "    # Check if 'JLCPCB Part #' is empty\n",
    "    if not part_details.get('JLCPCB Part #'):\n",
    "        return None\n",
    "\n",
    "    return part_details\n",
    "\n",
    "# Test the function with a specific lcsc_id\n",
    "lcsc_id = \"C25744\"\n",
    "data = get_lcsc_data(lcsc_id)\n",
    "data\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 94,
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "\n",
    "def get_lcsc_data(lcsc_id):\n",
    "\n",
    "    url = f'https://jlcpcb.com/partdetail/{lcsc_id}'\n",
    "\n",
    "    # Get the HTML content\n",
    "    response = requests.get(url)\n",
    "\n",
    "    # Check if the request was successful\n",
    "    if response.status_code != 200:\n",
    "        return None  # Or some error handling\n",
    "\n",
    "    # Parse the HTML content\n",
    "    soup = BeautifulSoup(response.text, 'html.parser')\n",
    "    # Find the section with the specifications or attributes\n",
    "    # This will depend on the actual structure of your HTML, but let's assume it's within a div with a specific class\n",
    "    spec_div = soup.find('div', class_='spec-comp-box')\n",
    "\n",
    "    # If the div is not found, try another method or print an error message\n",
    "    if not spec_div:\n",
    "        print(\"Specification section not found.\")\n",
    "    else:\n",
    "        # Dictionary to store the attributes\n",
    "        attributes = {}\n",
    "\n",
    "        # Assuming each attribute is in a separate 'div' within the 'spec-comp-box' div\n",
    "        attribute_divs = spec_div.find_all('div', recursive=False)\n",
    "\n",
    "        for div in attribute_divs:\n",
    "            # The structure within each 'div' might contain the attribute name and value\n",
    "            # Extract the attribute name and value based on your HTML structure\n",
    "            attribute_name = div.find('div', class_='attribute-name-class').text  # Replace with actual class or tag\n",
    "            attribute_value = div.find('div', class_='attribute-value-class').text  # Replace with actual class or tag\n",
    "            attributes[attribute_name] = attribute_value\n",
    "\n",
    "        # Print the extracted attributes\n",
    "        for attr_name, attr_value in attributes.items():\n",
    "            print(f\"{attr_name}: {attr_value}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 95,
   "metadata": {},
   "outputs": [
    {
     "ename": "AttributeError",
     "evalue": "'NoneType' object has no attribute 'text'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[95], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[43mget_lcsc_data\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mC25744\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m)\u001b[49m\n",
      "Cell \u001b[0;32mIn[94], line 34\u001b[0m, in \u001b[0;36mget_lcsc_data\u001b[0;34m(lcsc_id)\u001b[0m\n\u001b[1;32m     29\u001b[0m attribute_divs \u001b[38;5;241m=\u001b[39m spec_div\u001b[38;5;241m.\u001b[39mfind_all(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mdiv\u001b[39m\u001b[38;5;124m'\u001b[39m, recursive\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mFalse\u001b[39;00m)\n\u001b[1;32m     31\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m div \u001b[38;5;129;01min\u001b[39;00m attribute_divs:\n\u001b[1;32m     32\u001b[0m     \u001b[38;5;66;03m# The structure within each 'div' might contain the attribute name and value\u001b[39;00m\n\u001b[1;32m     33\u001b[0m     \u001b[38;5;66;03m# Extract the attribute name and value based on your HTML structure\u001b[39;00m\n\u001b[0;32m---> 34\u001b[0m     attribute_name \u001b[38;5;241m=\u001b[39m \u001b[43mdiv\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfind\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mdiv\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mclass_\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mattribute-name-class\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m)\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mtext\u001b[49m  \u001b[38;5;66;03m# Replace with actual class or tag\u001b[39;00m\n\u001b[1;32m     35\u001b[0m     attribute_value \u001b[38;5;241m=\u001b[39m div\u001b[38;5;241m.\u001b[39mfind(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mdiv\u001b[39m\u001b[38;5;124m'\u001b[39m, class_\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mattribute-value-class\u001b[39m\u001b[38;5;124m'\u001b[39m)\u001b[38;5;241m.\u001b[39mtext  \u001b[38;5;66;03m# Replace with actual class or tag\u001b[39;00m\n\u001b[1;32m     36\u001b[0m     attributes[attribute_name] \u001b[38;5;241m=\u001b[39m attribute_value\n",
      "\u001b[0;31mAttributeError\u001b[0m: 'NoneType' object has no attribute 'text'"
     ]
    }
   ],
   "source": [
    "get_lcsc_data('C25744')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
